# Generated by Django 5.2 on 2026-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_create_hypertable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telemetryreading",
            options={"managed": True, "ordering": ["-received_at"]},
        ),
    ]
